quarkiverse/quarkus-vault

- integration-tests/vault/src/test/java/io/quarkus/vault/VaultPKIITCase.java
- runtime/src/main/java/io/quarkus/vault/runtime/client/secretengine/VaultInternalPKISecretEngine.java
This only applies to the `VaultInternalPKISecretEngine.getRaw`. Previously when fetching an empty CA Chain or CRL it would thow a NPE, now it returns an empty list.
> PKI: Return an empty buffer instead of null when Vault returns 204

- docs/modules/ROOT/pages/includes/attributes.adoc
- integration-tests/vault/src/test/java/io/quarkus/vault/VaultSysITCase.java
- model/src/main/java/io/quarkus/vault/runtime/client/dto/sys/VaultSecretEngineInfoData.java
- model/src/main/java/io/quarkus/vault/runtime/client/dto/sys/VaultSecretEngineInfoResult.java
- runtime/src/main/java/io/quarkus/vault/VaultSystemBackendEngine.java
- runtime/src/main/java/io/quarkus/vault/runtime/VaultSystemBackendManager.java
- runtime/src/main/java/io/quarkus/vault/runtime/VaultVersions.java
- runtime/src/main/java/io/quarkus/vault/runtime/client/backend/VaultInternalSystemBackend.java
- runtime/src/main/java/io/quarkus/vault/sys/VaultSecretEngineInfo.java
- test-framework/src/main/java/io/quarkus/vault/test/VaultTestExtension.java
Implement a new endpoint `getMountInfo(String)` on the `VaultSystemBackendEngine`
Use it in `VaultSystemBackendManager.isEngineMounted(String)` when possible (starting in `1.10`)
Upgrade Vault to `1.10`
See https://github.com/hashicorp/vault/issues/12349
> Support GET sys/mounts/:path

- deployment/pom.xml
- runtime/pom.xml
- runtime/src/main/java/io/quarkus/vault/runtime/VaultAuthManager.java
Uses a Caffeine cache with a 1 hour expiry to hold wrapping tokens.
Ostensibly wrapping tokens should be used immediately. The 1 hour window is just to ensure an adequite time window in case of errors or retries.
Fixes #51
> Expire wrapping token cache

- .github/project.yml
last release before switching main to `3.0.0`, and moving to quarkus `3.0.0.Alpha1`
> Release 2.1.0

- runtime/src/main/java/io/quarkus/vault/runtime/client/SharedVertxVaultClient.java
This is needed because the VertxVaultClient can potentially be used inside a Synthetic bean and in such cases
obtaining Vertx which is itself a synthetic bean is not possible
Fixes: #78
> Avoid obtaining Vertx from CDI

- model/src/main/java/io/quarkus/vault/runtime/client/dto/AbstractVaultDTO.java
- runtime/src/main/java/io/quarkus/vault/runtime/client/VaultClientException.java
- runtime/src/main/java/io/quarkus/vault/runtime/client/VertxVaultClient.java
When a request expecting a 204 returns warnings it does so by returning a standaard 200 response with the warnings attached. Previously this would result in an exception becaues of the mismatched response status code.
Any Vault response can attach warnings. Those warnings are now logged for all responses.
> Handle warning only responses and log warnings

- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/vault-datasource.adoc
The `create` capability is needed for adding a new key step asked in the [`Programmatic access to the KV secret engine section`](https://quarkiverse.github.io/quarkiverse-docs/quarkus-vault/dev/index.html#_programmatic_access_to_the_kv_secret_engine)
> doc: add create capability to the policy

- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-vault.adoc
- integration-tests/vault/src/test/java/io/quarkus/vault/WiremockProxy.java
- model/src/main/java/io/quarkus/vault/runtime/client/dto/sys/VaultHealthResult.java
- model/src/main/java/io/quarkus/vault/runtime/client/dto/sys/VaultSealStatusResult.java
- pom.xml
- runtime/src/main/java/io/quarkus/vault/runtime/VaultSystemBackendManager.java
- runtime/src/main/java/io/quarkus/vault/sys/VaultHealthStatus.java
- runtime/src/main/java/io/quarkus/vault/sys/VaultSealStatus.java
- test-framework/src/main/java/io/quarkus/vault/test/VaultTestExtension.java
needed to rename field `sealed` because of error generated in `impsort`: `(line 11,col 12) Parse error. Found "sealed", expected one of  "enum" "exports" "module" "open" "opens" "provides" "record" "requires" "strictfp" "to" "transitive" "uses" "with" "yield" <IDENTIFIER>
`
> quarkiverse-parent 15

- .github/dependabot.yml
- pom.xml
No need to redefine the `maven-compiler-plugin` version
> Reuse maven-compiler-plugin version from parent

- docs/modules/ROOT/pages/vault-datasource.adoc
> Add documentation about needed recycling for db credentials provider

- deployment/pom.xml
- integration-tests/vault-app/pom.xml
- pom.xml
- runtime/pom.xml
- test-framework/pom.xml
This creates a `quarkus-vault-bom` to facilitate overriding versions when used in a project with the `quarkus-bom`(the extension modules are [included in the quarkus-bom](https://github.com/quarkusio/quarkus-platform/blob/8a3f9bfd51b83af3f3b2b50c71c2e1a10a5aa153/generated-platform-project/quarkus-universe/bom/pom.xml#L7797-L7811))
> Generate quarkus-vault-bom

- docs/modules/ROOT/pages/vault-auth.adoc
- docs/modules/ROOT/pages/vault-datasource.adoc
- docs/modules/ROOT/pages/vault-pki.adoc
- docs/modules/ROOT/pages/vault-transit.adoc
Proof of all warnings gone:
Proof of warnings before this PR:
@gastaldi @vsevel when you have a bit of time please review :)
> Fix asciidoc warnings

- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-vault.adoc
- pom.xml
- runtime/src/main/java/io/quarkus/vault/runtime/client/SharedVertxVaultClient.java
Fixes `VertxRecorder` removal in `3.4`
In `3.5` we will use https://github.com/quarkiverse/quarkus-vault/pull/167, benefiting from https://github.com/quarkusio/quarkus/pull/35949
cc @kdubb @gsmet @geoand 
Fixes https://github.com/quarkiverse/quarkus-vault/issues/165
> Bump to Quarkus 3.4.0 - Replace VertxRecorder with VertxEventBusConsumerRecorder

- .github/project.yml
> Release 3.2.0

- docs/modules/ROOT/pages/includes/attributes.adoc
The `dependabot` did an excelent automated job on updating the dependency of `Quarkus` framework to use for the project after checking the build process but missed to update the `attributes.adoc` file to set up the right version of used Quarkus framework
> Update Quarkus version on attributes.adoc file

- .github/workflows/build.yml
- .github/workflows/quarkus-snapshot.yaml
- .github/workflows/release.yml
The purpose of this pull request is to update the `Github actions` to latest stable ones and use to wrapped stable `maven` version 3.9.5 distribution to for building the project on` Github actions CI`, also open the build on users  branches to be sure the build is stable before making a pull request and of course disable that build in case of dependent bot pushed, `wip` branches and draft onces 
- enable the build process on user branches 
- update `checkout` actions to the latest stable version 4
- update `cache` actions to the latest stable version 4
- update the `setup-java` actions to the latest stable version 3 
- update `Github actions` for snapshot and release
- enable build on branches intended  to make pull requests
> Use latest stable tools on Github actions with the maven wrapped version

- deployment/src/main/java/io/quarkus/vault/deployment/DevServicesVaultProcessor.java
- integration-tests/vault/src/test/java/io/quarkus/vault/VaultPKIITCase.java
- runtime/src/main/java/io/quarkus/vault/VaultPKISecretEngine.java
- runtime/src/main/java/io/quarkus/vault/runtime/VaultVersions.java
- test-framework/src/main/java/io/quarkus/vault/test/VaultTestExtension.java
The main purpose of this pull request is to use the latest stable version of vault image on `hashicorp/vault` instead the already used one `vault`, as mentioned on https://hub.docker.com/_/vault/  that Upcoming in Vault 1.14, we will stop publishing official `Dockerhub` images and publish only our Verified Publisher images. Users of `Docker` images should pull from [hashicorp/vault](https://hub.docker.com/r/hashicorp/vault) instead of [vault](https://hub.docker.com/_/vault). Verified Publisher images can be found at https://hub.docker.com/r/hashicorp/vault` on this pull request, an update of a recent version of `vault` can keep fresh the library and make it fit to the upcoming new changes and prevent the drastic changes when a lot of breaking changes happens on certain versions 
- Update …
> Update version of vault image to latest stable official image 1.15.0 

- pom.xml
The purpose of this pull request is to move the version. of wiremock to the latest stable one 3.0.1 to get benefits of that much improvement and bug fixings
For more information about the release notes please refer to : https://github.com/wiremock/wiremock/releases/tag/3.2.0 and to get a deep insight since the last used version, please check https://github.com/wiremock/wiremock/compare/2.27.2...3.2.0
> Upgrade version of Wiremock to 3.0.1

- docs/modules/ROOT/pages/includes/attributes.adoc
- integration-tests/vault/pom.xml
- integration-tests/vault/src/test/java/io/quarkus/vault/VaultPKIITCase.java
- pom.xml
- runtime/src/main/java/io/quarkus/vault/runtime/client/SharedVertxVaultClient.java
supersedes https://github.com/quarkiverse/quarkus-vault/pull/167 @geoand 
relates to https://github.com/quarkusio/quarkus-platform/pull/1002#issuecomment-1757889375 @gsmet 
strangely, I had to rework the assertions on the pki test. what do you think @kdubb ?
> Quarkus 3.5.0.CR1 + Don't use VertxRecorder to get Vertx instance

- docs/modules/ROOT/pages/index.adoc
- integration-tests/vault/src/test/java/io/quarkus/vault/VaultITCase.java
- integration-tests/vault/src/test/resources/application-vault.properties
- runtime/src/main/java/io/quarkus/vault/runtime/config/VaultConfigSource.java
- test-framework/src/main/java/io/quarkus/vault/test/VaultTestExtension.java
- test-framework/src/main/resources/config.json
- test-framework/src/main/resources/vault.policy
This pull request modify the way VaultConfigSource fetches the values from Vault following recommendation made by @vsevel 
Now, it fetches the value as Object and convert it to String if type is not List or Map.  
null value is also managed.  
Also add a note in documentation to mention that list and map are not yet supported.
resolve quarkiverse/quarkus-vault#189
> Support scalar value other than String from Vault

- deployment/src/main/java/io/quarkus/vault/deployment/DevServicesVaultProcessor.java
This fixes dev services by using the correct scheme, HTTP, when connecting to automatically started dev services containers.
@vsevel I'm thinking we revert this to HTTP instead of passing the new `-dev-tls` flag and using HTTPS. My reasoning is just, as we've discussed previously, security products are generally updated slowly and the new flag requires Vault `1.12+`.
We could selectively enable TLS but we'd need to be figuring it out prior to container startup based on the image tag. It can be done it's just work I don't have time for and we need to get this back in working order.
Also, we really need to add a unit test that actually uses a proper "dev services" container. Unfortunately I'm swamped at the moment.
> Revert to using HTTP when connecting to dev services containers

- client/src/main/java/io/quarkus/vault/client/common/VaultRequest.java
- runtime/src/main/java/io/quarkus/vault/runtime/client/VaultClientProducer.java
Read timeout was previously set on the VertxVaultHttpClient client but not on JDK. This applies the read timeout to JDKVaultHttpClient
Fixes #253
> Allow applying a read timeout to JDKVaultHttpClient

- runtime/src/main/java/io/quarkus/vault/runtime/client/JDKClientFactory.java
- runtime/src/main/java/io/quarkus/vault/runtime/client/MutinyVertxClientFactory.java
- runtime/src/main/java/io/quarkus/vault/runtime/client/VaultClientProducer.java
This is done because with the advent of Quarkus 3.12 and the new TLS Registry, the TlsConfig config object is no longer valid.
By using the property we can now support all versions of Quarkus
> Use quarkus.tls.trust-all property directly

- client/src/main/specs/sys/health.yaml
- client/src/main/specs/sys/init.yaml
This fixes the API spec files so that the generated parameters are named exactly like in the Vault API documentation, e.g. `standbyok` has to be all-lowercase and `root_token_p_g_p_key` had too many underscores.
> Fix API parameter names

- docs/modules/ROOT/pages/includes/attributes.adoc
- test-framework/src/main/java/io/quarkus/vault/test/VaultTestExtension.java
Fixes #315 
Let me know if there is a place where to test this.
> Allow configuring different images for Postgres and RabbitMQ in testing

- docs/modules/ROOT/pages/includes/attributes.adoc
- integration-tests/vault/src/test/java/io/quarkus/vault/VaultITCase.java
- runtime/src/main/java/io/quarkus/vault/runtime/VaultCredentialsProvider.java
- test-framework/src/main/java/io/quarkus/vault/test/VaultTestExtension.java
- test-framework/src/main/resources/cred-provider.json
Fixes https://github.com/quarkiverse/quarkus-vault/issues/327
Supersedes https://github.com/quarkiverse/quarkus-vault/pull/329
> handle null values in secrets loaded by the credentials provider

- runtime/src/main/java/io/quarkus/vault/runtime/health/VaultHealthCheck.java
In #320 I already fixed an issue with letter casing for the two health check query params `standbyok` and `perfstandbyok`, now we noticed that these two options are never ever being used in production. `VaultHealthCheck#call` only calls the parameter-less `status()` method instead of the method accepting two parameters for `standbyok` and `perfstandbyok`, so the config parameters were actually ineffective altogether.
This PR fixes this behavior.
> Actually pass standby-ok config params to health check

- client/src/main/java/io/quarkus/vault/client/VaultClient.java
- client/src/main/java/io/quarkus/vault/client/auth/VaultAppRoleTokenProvider.java
- client/src/main/java/io/quarkus/vault/client/auth/VaultCachingTokenProvider.java
- client/src/main/java/io/quarkus/vault/client/auth/VaultKubernetesTokenProvider.java
- client/src/main/java/io/quarkus/vault/client/auth/VaultTimeLimited.java
- client/src/main/java/io/quarkus/vault/client/auth/VaultToken.java
- client/src/main/java/io/quarkus/vault/client/auth/VaultTokenException.java
- client/src/main/java/io/quarkus/vault/client/auth/VaultUserPassTokenProvider.java
- client/src/main/java/io/quarkus/vault/client/common/VaultTracingExecutor.java
- client/src/test/java/io/quarkus/vault/client/VaultCachingTokenProviderTest.java
- client/src/test/java/io/quarkus/vault/client/VaultClientRetryTest.java
- client/src/test/java/io/quarkus/vault/client/test/TickableInstantSource.java
- client/src/test/java/io/quarkus/vault/client/test/VaultClientTestExtension.java
- client/src/test/resources/trace-log.properties
- docs/modules/ROOT/pages/includes/attributes.adoc
Fixes #338
While enhancing the test for caching tokens I realized supporting limited use tokens should be fairly straightforward.
@vsevel What do you think? The only tricky thing is that we copy token values (e.g., for caching) so I used an `AtomicReference` as a shared reference count. Other than that, I added `getClientTokenForUsage` to decrement the count when it's being used for authorization and overloaded the expiration tests to take into account it's max # of uses.
I added a test to the caching token provider tests suite that tests limited use tokens and it seems to perform as expected.
It does not attempt to `extend` limited use tokens that are over their use limit because from my investigation it doesn't seem that's allowed.
@alexjaravete Can you build this this locally and see …
> Support refresh of limited use tokens (num_use > 0)

- docs/modules/ROOT/pages/vault-transit.adoc
- integration-tests/vault-app/src/main/resources/application.properties
- integration-tests/vault/src/test/java/io/quarkus/vault/VaultITCase.java
- integration-tests/vault/src/test/java/io/quarkus/vault/VaultTransitITCase.java
- integration-tests/vault/src/test/resources/application-vault.properties
- runtime/src/main/java/io/quarkus/vault/runtime/VaultTransitManager.java
- runtime/src/main/java/io/quarkus/vault/runtime/config/VaultRuntimeConfig.java
- test-framework/src/main/java/io/quarkus/vault/test/VaultTestExtension.java
- test-framework/src/main/resources/vault.policy
This adds `quarkus.vault.transit-secret-engine-mount-path` config property.
Behaviour is the same as `quarkus.vault.kv-secret-engine-mount-path`.
> Add config property to configure transit secret engine mount path

- deployment/src/main/java/io/quarkus/vault/deployment/DevServicesVaultProcessor.java
- docs/modules/ROOT/pages/includes/attributes.adoc
GlobalDevServicesConfig will be dropped in Quarkus 3.26 (we deprecated it in Quarkus 3.19).
> Switch to using DevServicesConfig

- docs/modules/ROOT/pages/index.adoc
- integration-tests/vault/src/test/java/io/quarkus/vault/VaultKvSecretEngineV1AliasITCase.java
- integration-tests/vault/src/test/java/io/quarkus/vault/VaultKvSecretEngineV2AliasITCase.java
- integration-tests/vault/src/test/resources/application-vault-secret-engine-mount-path-v1.properties
- integration-tests/vault/src/test/resources/application-vault-secret-engine-mount-path-v2.properties
- runtime/src/main/java/io/quarkus/vault/VaultKVSecretReactiveEngine.java
- runtime/src/main/java/io/quarkus/vault/runtime/VaultKvManager.java
- runtime/src/main/java/io/quarkus/vault/runtime/config/VaultConfigSource.java
- runtime/src/main/java/io/quarkus/vault/runtime/config/VaultRuntimeConfig.java
- runtime/src/main/java/io/quarkus/vault/runtime/kv/KvV1.java
- runtime/src/main/java/io/quarkus/vault/runtime/kv/KvV2.java
- runtime/src/main/java/io/quarkus/vault/runtime/kv/VersionedKv.java
this bring support named kv secret engines with their mount path, version and `secret-config-kv-path`.
for instance for a `v1` engine:
```
quarkus.vault.kv-secret-engine."myengine1".version=1
quarkus.vault.kv-secret-engine."myengine1".mount-path=secret-v1
quarkus.vault.kv-secret-engine."myengine1".secret-config-kv-path=foo
quarkus.vault.kv-secret-engine."myengine1".secret-config-kv-path."myfoo"=foo
```
and for `v2`:
```
quarkus.vault.kv-secret-engine."myengine2".version=2
quarkus.vault.kv-secret-engine."myengine2".mount-path=secret
quarkus.vault.kv-secret-engine."myengine2".secret-config-kv-path=foo
quarkus.vault.kv-secret-engine."myengine2".secret-config-kv-path."myfoo"=foo
```
the default engine (with mount path `secret` and version 2) is still available, and can be used alongside the …
> Support Multiple KV Secret Engines
